"use client";
import TicketProvider from "./api/datacontext";
import Footer from "./footer";
import "./globals.css";
import Navbar from "./navbar";

export const metadata = {
  title: "Movie Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TicketProvider>
          <Navbar />
          {children}
          <Footer />
        </TicketProvider>
      </body>
    </html>
  );
}
